#TreasureHuntQuest
treasure.id=treasure-hunt
treasure.genre=Хоррор/Приключения
treasure.difficulty=3
treasure.image=/images/castle.jpg
treasure.victoryIds=7,8,9,12

#SpaceAdventureQuest
space.id=space-adventure
space.genre=Выживание
space.difficulty=4
space.image=/images/space.jpg
space.victoryIds=7,9

#DetectiveStoryQuest
detective.id=detective-story
detective.genre=Детектив/Мистика
detective.difficulty=5
detective.image=/images/mansion.jpg
detective.victoryIds=7,9,12


